name: Run Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  Airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Check current user
        run: whoami
        
      - name: Pull and run Docker image
        run: |
      
          docker pull atul7717/airflow:latest
          docker run -u root -d --name airflow atul7717/airflow:latest  

      - name: Run Airflow
        run: |
          docker exec airflow which airflow
          docker exec airflow echo $PATH
