name: Trigger Airflow DAG
on:
  push:
    branches:
      - feature_manish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Trigger Airflow DAG
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          export AIRFLOW_HOME=/root/airflow/
          sudo whoami
          sudo su
          sudo source /home/airflow_workspace/airflow_env/bin/activate
          sudo airflow users list
          sudo airflow version
          sudo airflow dags trigger s3_copy_objects
