name: Run Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  Airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Check current user
        run: whoami
        
      - name: Pull and run Docker image
        run: |
      
          docker pull atul7717/airflow:latest
          docker run -u root -d --name airflow atul7717/airflow:latest


      - name: Run command inside the container
        run: |
          docker exec airflow ls /usr/src/app
          docker exec airflow pip install --upgrade pip
          docker exec airflow pip show airflow
          docker exec airflow pip list

