name: Trigger Airflow DAG
on:
  push:
    branches:
      - feature_manish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Trigger Airflow DAG
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          whoami
          sudo su
          source /home/airflow_workspace/airflow_env/bin/activate
          airflow users list
          airflow version
          airflow dags trigger s3_copy_objects
