name: Run Airflow DAGs

on:
  push:
    paths:
      - 'dags/**'
    branches:
      - feature_dataops

jobs:
  Airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Check current user
        run: whoami
        
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Confirm Black code compliance fo DAGs
        run: |
          pip install pytest-black==0.3.12
          pytest Copy_data_Dag.py  -v
