name: Run Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  Airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Check current user
        run: whoami
        
      - name: Pull and run Docker image
        run: |
      
          docker pull atul7717/airflow:latest
          docker run -u root -d --name airflow_container atul7717/airflow:latest  

      - name: Run Airflow
        run: |
          docker exec airflow db init
          docker exec airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email tech@glabinnovation.com
          docker exec airflow webserver -D &
          docker exec airflow scheduler -D &
          sleep 10
