name: Run Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  Airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Check current user
        run: whoami
        
      - name: Pull and run Docker image
        run: |
      
          docker pull atul7717/airflow:latest
          docker run -u root -d --name airflow atul7717/airflow:latest  
          
      - name: Debug Airflow installation
        run: |
          docker exec airflow python -c "import sys; print(sys.path)"
          docker exec airflow pip show apache-airflow
    

      - name: Run Airflow
        run: |
          docker exec airflow which airflow
          docker exec airflow echo $PATH
          docker exec airflow airflow db init
          docker exec airflow airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email tech@glabinnovation.com
          docker exec airflow airflow webserver -D &
          docker exec airflow airflow scheduler -D &
          sleep 10
